language: node_js
sudo: true
node_js:
  - "7"

demo/dist: trusty

branches:
  only:
  - master

script: 
  - npm run lint
  - node_modules/.bin/karma start --single-run --no-fail-on-empty-test-suite
  - cd demo
  - yarn
  - node_modules/.bin/webdriver-manager update
  - node_modules/.bin/ng test --watch false
  - npm run e2e
  - ng build -bh "https://koderlabs.github.io/ng2-device-detector/" --prod --aot

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: demo/dist
  on:
    branch: master