language: node_js
sudo: true
node_js:
  - "7"

demo/dist: trusty

branches:
  only:
  - master

before_script:
- export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i --force-depends ~/google-chrome-stable_current_amd64.deb
 - npm install -g yarn

script: 
  - npm run lint
  - node_modules/.bin/karma start --single-run --no-fail-on-empty-test-suite
  - cd demo
  - yarn
  - node_modules/.bin/ng test --watch false
  - node_modules/.bin/webdriver-manager update
  - npm run e2e
  - ng build -bh "https://koderlabs.github.io/ng2-device-detector/" --prod --aot

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: demo/dist
  on:
    branch: master